### PR TITLE
Resolving issues for a Bluemix App Deployment

### PR DESCRIPTION
**Pull request by hobertbush**
Worked with @jmkanz to resolve the connection related issues.

### CODE REVIEW

**Comment by hobertbush** [comment]
Please let us @hobertbush or @jmkanz know if you have any questions.

**Comment by jedidiahwahana** [comment]
Hi Hobert and Justin,
I have tried the code, but these errors come out, can you guide me through it? Thanks!

Best regards,
Jedidiah

screen shot 2017-03-10 at 6 29 08 pm
screen shot 2017-03-10 at 6 29 36 pm
screen shot 2017-03-10 at 6 29 53 pm

**Comment by hobertbush** [comment]
Please update the Line 7 of this code with the hostname of the db:

https://github.com/jedidiahwahana/springelephant-2/blob/master/src/main/java/com/linecorp/example/springelephant/db/DbContract.java

You'll also need to add the username and password in the fields as well.

**Comment by jedidiahwahana** [comment]
Hi Hobert,
Thanks for responding. I've missed to edit that before. I've edited now and it's still can't connect to the database, there is an error about UnknownHostException. I attached the screenshot of the errors. Thanks.

Best regards,
Jedidiah

screen shot 2017-03-13 at 11 35 28 am
screen shot 2017-03-13 at 11 35 42 am
screen shot 2017-03-13 at 11 35 56 am
screen shot 2017-03-13 at 11 36 17 am

**Comment by jedidiahwahana** [comment]
Below is the updated DbContract.java

screen shot 2017-03-13 at 11 39 03 am

**Comment by hobertbush** [comment]
Thank you. Please change the hostname in the DB_URL to the following:

public static final String DB_URL= "jdbc:postgresql://echo-01.db.elephantsql.com:5432/fkycikzy";
 }

The username and password will be picked up from the other values.

**Comment by jedidiahwahana** [comment]
Hi Hobert,
Thank you so much for your guidance, I'm able to connect to the database now.

Cheers!
Jedidiah

**Pull request merged**
